id: 0
id_ip:
    0: 0.0.0.0
    1: 0.0.0.0
    2: 0.0.0.0
    3: 0.0.0.0
id_name:
    0: node0
    1: node1
    2: node2
    3: node3
id_p2p_port:
    0: 9000
    1: 9001
    2: 9002
    3: 9003
id_public_key:
    0: QmPQK4xeUZgrFqW8W1XbSy8mZ3N8rPvMPyXCZee5UYZjtf
    1: QmTDvHej87Sctdwy33KEz5Pn1k7FyfgQ5PM4tfN114bC6H
    2: QmbV2KPyeL6TAY3heJVmLGUGtYmNXXSNb4MEJ9wscHCtrB
    3: QmdvsVVhY7svCZPkirzZFfWVznWp8ZrhGDYBNSsG9hYByx 
ip: 0.0.0.0
node_number: 4
nodename: node0
p2p_port: 9000
private_key: CAASqAkwggSkAgEAAoIBAQDAfgYYlIVZxVmjWnb3tydj7RMtsjw8e0KNDViYGc3bW5r4d023txVslmbGp9rrodxDq8cJ7HCj9gzOs4a2cYc9kDDDCcL4GBfBmviYOTaP3RzTqD0woKjTRKI3wbcMJ0Fnct19QIz7w24q8gcmuiZtw0gnluXP4OTbe67IEZKPSrxH0HreM3UAeKHWKteT2qwF1EANjSvIGTsQO2amSLojqEOMW4jnkYezxEo2XiUKvc2IULXOmCPLvRkJCoTYtZtb+tbsGAQlscUrAbD968Xd0NbUwxyvWRprWs/gaPhhVaM1PPOznJPQzySRWerTJotjr1R0s0KrQbl4pTu2wsovAgMBAAECggEAbxJJAjXxHHO73X5910JgAFD0GBIYn+2f4TQqQtng5wpcybJNrgx+2EGQ3GBO+lhTeNjN6PP9qx53FW6R9QRdPTDOcjxXvEBqtNRvTab1zN2RnLAfXsfVotKfp/ynWuPr4X1uQK/Wqg+CqlUtuzL+qaddIzr3MJRceilMGTXKk9NR15Ors7o8hW7m/X43XvwKpP5YW5sMjtQM6sf3xMIwO4OHWpzAHDM5aGiFxntza6io/Dpd3mHGjZu1bnIhM2GN0xinkVuJf87j7vnmB0MrLis96+6LK0gd0L5lLi+wtVeIKy1NQMptuOcPz1y71ru+mpAUgqh295QZWPfiwf9lAQKBgQD7V/yneWgUlllIq6OsApME2/oNbJs6nK3OmlKirksB+hgIlSDhXoDblyi20/ZqvJSpRmxGiEV2mvJLlgucNyxIdfU8flDUnvASvD0cdMNT9vpsd+u1XoeJdJcFx3Gnyti+GzompEvEoL52uqCtyFcIkKNBR7jUyCAVs2i9YUHJ/wKBgQDEDu4tkbRbtILOAdIlCJCJiFl8DWX/1VwuIkH/udwbt+qnLxdhO7TWmbJ/FQ+MHY3ldNTSwYhQC3Z1pWs5nM5dpO99OX7d46IZIPWBFediyGl6ZhJw1cBx+vXmEM8/AcVtjw+v/Y3okJg6qFWfQm7AJDzErweUEU55tdjtgWkf0QKBgQDV0CC/O1leAhSL7G88magFvzg1iUl4D+cPVVqsx4ZJdT5StsIU1jbaFvnspd3/KNNyONVNHwmwftlVkZvo1UqXjbkEMBSE+3wRBA8ckPvFBto7wbxDOtokBYmfwe2epsHA3xqV2rgV2gSMrfCYRVA8mgY3N1M1t9ULgOa+C+lScwKBgEedeIz2sx3oYvtjGOLkLP+/6Yfx0PdRdVl4tAj4WBlb5f/pqK2gxJ67B8N56vLwfLt7IJ5XiTZL6ZpxsSgbShpUvBJO5TOiCb0KGANt/9ZKhJTsIgJLYf+Afz/plfpa6EXrwvwzLxnrb1/Fy3jgKFpRIk1p7ee9JqA4t6OR6NdxAoGBANCP73v6fubd6YiZDzYxS4L39+8VtQCHfQwNTZsuLjHFfUIfCJCzS20muAc3u75hC96+3JStI09UQn875rzcCVNNtk4VIbYJuTigxFfSf3rSNC95uUpHEawy7CM0WnywLUd5WgIHfBNc+LdAe2OqeYdSQuacTrW18jrKI0RANDCa
public_key: CAASpgIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDAfgYYlIVZxVmjWnb3tydj7RMtsjw8e0KNDViYGc3bW5r4d023txVslmbGp9rrodxDq8cJ7HCj9gzOs4a2cYc9kDDDCcL4GBfBmviYOTaP3RzTqD0woKjTRKI3wbcMJ0Fnct19QIz7w24q8gcmuiZtw0gnluXP4OTbe67IEZKPSrxH0HreM3UAeKHWKteT2qwF1EANjSvIGTsQO2amSLojqEOMW4jnkYezxEo2XiUKvc2IULXOmCPLvRkJCoTYtZtb+tbsGAQlscUrAbD968Xd0NbUwxyvWRprWs/gaPhhVaM1PPOznJPQzySRWerTJotjr1R0s0KrQbl4pTu2wsovAgMBAAE=
